trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - template: /azure/steps/download-url-to-file.yml
    parameters:
      name: 'downloadfile'
      source_url: 'https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/windows/apktool.bat'
      target_path_including_filename: '$(Pipeline.Workspace)/apk-tool.bat'
      file_path_variable: 'download_path'
  
  - script: echo $(downloadfile.download_path)