trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - template: download-url-to-file.yml
    parameters:
      source_url: 'https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/windows/apktool.bat'
      target_path_including_filename: '$(Pipeline.Workspace)/apk-tool.bat'
