trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  paths:
    include:
    - src/apps/dotnet/xamarin/SimpleUnoApp/*
    - azure/stages/build-and-deploy-uno.yml
    - azure/stages/build-solution.yml
    - src/apps/dotnet/xamarin/pipeline/simpleunoapp.yml
  
variables:
  - group: 'Common Variables'
  - group: 'Apps Variables'
  - group: 'DotNet Variables'
  - group: 'Xamarin Variables'
  - name: DISABLE_NODE6_DEPRECATION_WARNING
    value: true

stages:
- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Do_Nothing'
    solution_filename: $(uno_solution_file)

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Solution_Build_Only'
    solution_filename: $(uno_solution_file)
    full_version_number: '$(version_prefix).$(Build.BuildId)'
    solution_build_enabled: true

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Skip_Solution_Build'
    solution_filename: $(uno_solution_file)
    full_version_number: '$(version_prefix).$(Build.BuildId)'
    wasm_enabled: true
    wasm_project_file: $(uno_wasm_project_name)
    banner_enabled: true

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Build_Everything'
    solution_filename: $(uno_solution_file)
    solution_build_enabled: true
    wasm_enabled: true
    wasm_project_file: $(uno_wasm_project_name)

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Build_And_Deploy_Wasm'
    solution_filename: $(uno_solution_file)
    solution_build_enabled: false
    wasm_enabled: true
    wasm_project_file: $(uno_wasm_project_name)
    deploy_enabled: true
    azure_subscription_connection_name: $(azure_connection_name)
    wasm_static_app_name: $(uno_wasm_static_web_app_name)
    resource_group_name: $(azure_resource_group)

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Build_And_Deploy_Android'
    solution_filename: $(uno_solution_file)
    solution_build_enabled: false
    android_enabled: true
    deploy_enabled: true
    appcenter_service_connection: $(appcenter_connection_name)
    appcenter_organisation: $(appcenter_organisation)
    appcenter_applicationid_android: $(appcenter_android_appid)

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Build_And_Deploy_iOS'
    solution_filename: $(uno_solution_file)
    solution_build_enabled: false
    ios_enabled: true
    ios_solution_filter: $(uno_ios_solution_filter)
    deploy_enabled: true
    appcenter_service_connection: $(appcenter_connection_name)
    appcenter_organisation: $(appcenter_organisation)
    appcenter_applicationid_ios: $(appcenter_ios_appid)

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Build_Everything_And_Deploy'
    solution_filename: $(uno_solution_file)
    solution_build_enabled: true
    wasm_enabled: true
    wasm_project_file: $(uno_wasm_project_name)
    android_enabled: true
    ios_enabled: true
    ios_solution_filter: $(uno_ios_solution_filter)
    deploy_enabled: true
    azure_subscription_connection_name: $(azure_connection_name)
    wasm_static_app_name: $(uno_wasm_static_web_app_name)
    resource_group_name: $(azure_resource_group)
    appcenter_service_connection: $(appcenter_connection_name)
    appcenter_organisation: $(appcenter_organisation)
    appcenter_applicationid_android: $(appcenter_android_appid)
    appcenter_applicationid_ios: $(appcenter_ios_appid)
