trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  paths:
    include:
    - src/apps/dotnet/xamarin/SimpleUnoApp/*
    - azure/stages/build-and-deploy-uno.yml
    - azure/stages/build-solution.yml
  
variables:
  - group: 'Common Variables'
  - group: 'Apps Variables'
  - group: 'DotNet Variables'
  - group: 'Xamarin Variables'
  - name: DISABLE_NODE6_DEPRECATION_WARNING
    value: true

stages:
- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Do_Nothing'
    solution_filename: $(uno_solution_file)

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Solution_Build_Only'
    solution_filename: $(uno_solution_file)
    full_version_number: '$(version_prefix).$(Build.BuildId)'
    solution_build_enabled: true

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Skip_Solution_Build'
    solution_filename: $(uno_solution_file)
    full_version_number: '$(version_prefix).$(Build.BuildId)'
    wasm_enabled: true
    wasm_project_file: $(uno_wasm_project_name)
    banner_enabled: true

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Build_Everything'
    solution_filename: $(uno_solution_file)
    solution_build_enabled: true
    wasm_enabled: true
    wasm_project_file: $(uno_wasm_project_name)

- template:  ../../../../../azure/stages/build-and-deploy-uno.yml
  parameters:
    name: 'UnoApp_Build_Everything_And_Deploy'
    solution_filename: $(uno_solution_file)
    solution_build_enabled: true
    wasm_enabled: true
    wasm_project_file: $(uno_wasm_project_name)
    deploy_enabled: true
