
trigger: none
  
variables:
  - group: 'Common Variables'
  - group: 'Apps Variables'
  - group: 'DotNet Variables'
  - group: 'Xamarin Variables'
  - name: DISABLE_NODE6_DEPRECATION_WARNING
    value: true

stages:
- template:  ../../../../../azure/stages/build-xamarin-ios.yml
  parameters:
    # Stage name and whether it's enabled
    stage_name: 'Build_iOS_Project_File'
    # Solution to build
    solution_filename: $(xamarin_ios_project_file)
    solution_build_configuration: $(solution_build_config)
    # Signing information
    ios_plist_filename: 'src/apps/dotnet/xamarin/XamarinApps/XamariniOSApp/Info.plist'
    ios_cert_password: '$(ios_signing_certificate_password)'
    ios_cert_securefiles_filename: '$(ios_signing_certificate_securefiles_filename)'
    ios_provisioning_profile_securefiles_filename: '$(ios_provisioning_profile_securefiles_filename)'
    # Output information
    artifact_folder: $(artifact_ios_folder)
    application_package: $(xamarin_ios_project_package)

- template:  ../../../../../azure/stages/build-xamarin-ios.yml
  parameters:
    # Stage name and whether it's enabled
    stage_name: 'Build_iOS_Solution_File'
    # Solution to build
    solution_filename: $(solution_file)
    solution_build_configuration: $(solution_build_config)
    # Signing information
    ios_plist_filename: 'src/apps/dotnet/xamarin/XamarinApps/XamariniOSApp/Info.plist'
    ios_cert_password: '$(ios_signing_certificate_password)'
    ios_cert_securefiles_filename: '$(ios_signing_certificate_securefiles_filename)'
    ios_provisioning_profile_securefiles_filename: '$(ios_provisioning_profile_securefiles_filename)'
    # Output information
    artifact_folder: $(artifact_ios_folder)
    application_package: $(xamarin_ios_solution_package)


- template:  ../../../../../azure/stages/build-xamarin-android.yml
  parameters:
    # Stage name and whether it's enabled
    stage_name: 'Build_Android_Project_File_AAB'
    # Project to build
    solution_filename: $(xamarin_android_project_file)
    solution_build_configuration: $(solution_build_config)
    solution_target_platform: $(android_project_target_platform)
    # Output information
    artifact_folder: $(artifact_android_folder)
    application_package: $(xamarin_android_project_package_name_aab)

- template:  ../../../../../azure/stages/build-xamarin-android.yml
  parameters:
    # Stage name and whether it's enabled
    stage_name: 'Build_Android_Project_File_APK'
    # Project to build
    solution_filename: $(xamarin_android_project_file)
    solution_build_configuration: $(solution_build_config)
    solution_target_platform: $(android_project_target_platform)
    # Output information
    artifact_folder: $(artifact_android_folder)
    application_package: $(xamarin_android_project_package_name_apk)

- template:  ../../../../../azure/stages/build-xamarin-android.yml
  parameters:
    # Stage name and whether it's enabled
    stage_name: 'Build_Android_Solution_File_AAB'
    # Solution to build
    solution_filename: $(solution_file)
    solution_build_configuration: $(solution_build_config)
    # Output information
    artifact_folder: $(artifact_android_folder)
    application_package: $(xamarin_android_solution_package_name_aab)

- template:  ../../../../../azure/stages/build-xamarin-android.yml
  parameters:
    # Stage name and whether it's enabled
    stage_name: 'Build_Android_Solution_File_APK'
    # Solution to build
    solution_filename: $(xamarin_android_project_file)
    solution_build_configuration: $(solution_build_config)
    solution_target_platform: $(android_project_target_platform)
    # Output information
    artifact_folder: $(artifact_android_folder)
    application_package: $(xamarin_android_solution_package_name_apk)
