parameters:
# stage_name - (Optional) The name of the stage, so that it can be referenced elsewhere (eg for dependsOn property). 
# Defaults to 'Build_Android'
- name: stage_name
  type: string
  default: 'Build_Android'
# depends_on - (Optional) The array of stages that this stage depends on. Default is that this stage does not depend on 
# any other stage
- name: depends_on
  type: string
  default: ''
# build_android_enabled - (Optional) Whether this stages should be executed. Note that setting this to false won't completely
# cancel the stage, it will merely skip most of the stages. The stage will appear to complete successfully, so
# any stages that depend on this stage will attempt to execute
- name: build_android_enabled
  type: boolean
  default: true

# build_number - (Optional) The build number to be applied to the application. Defaults to Build.BuildId 
# built in variable
- name: build_number
  type: string
  default: '$(Build.BuildId)'
# full_version_number - (Optional) The full application version number. Defaults to 1.0.XXX where XXX is the 
# same as the build_number
- name: full_version_number
  type: string
  default: '1.0.$(Build.BuildId)'

# solution_filename - (Required) The relative path to the solution file that should be built
- name: solution_filename
  type: string
# solution_build_configuration - (Optional) The build configuration within the solution that should be invoked. 
# Default is Release but can be overwritten if you want to do say a Debug build
- name: solution_build_configuration
  type: string
  default: Release
# solution_target_platform - (Optional) The target platform that the solution build will use. 
# Defaults to Any CPU
- name: solution_target_platform
  type: string
  default: 'Any CPU'

# android_manifest_filename - (Optional) The relative path to the AndroidManifest.xml file
# that defines the application manifest. If not specified, template will search for AndroidManifest.xml file
- name: android_manifest_filename
  type: string
  default: ''
# secure_file_keystore_filename - (Required) The keystore file used to sign the application. This is the name
# of the keystore in Secure Files
- name: secure_file_keystore_filename
  type: string
# keystore_password - (Required) The password to access the keystore
- name: keystore_password
  type: string
# key_alias - (Required) The alias of the key.
- name: key_alias
  type: string
# key_password - (Required) The password to access the key.
- name: key_password
  type: string

# artifact_name - (Optional) The name of the artifact to copy application to
- name: artifact_name
  type: string
  default: 'drop'
# artifact_folder - (Optional) The name of the folder to copy application to in the artifact
- name: artifact_folder
  type: string
  default: 'Android'
# application_package - (Optional) The name of the application package to output
- name: application_package
  type: string
  default: 'SignedAndroid.aab'

# onStart - (Optional) Steps to be executed before stage starts
- name: onStart
  type: stepList
  default: []
# preBuild - (Optional) Steps to be executed before the build starts
- name: preBuild
  type: stepList
  default: []
# postBuild - (Optional) Steps to be executed after the build has been invoked
- name: postBuild
  type: stepList
  default: []
# prePublish - (Optional) Steps to be executed before application package is published to artifact
- name: prePublish
  type: stepList
  default: []
# onEnd - (Optional) Steps to be executed at the end of the stage
- name: onEnd
  type: stepList
  default: []

# android_nuget_version - (Optional) Use to override the NuGet version (defaults to 5.9.1)
- name: android_nuget_version
  type: string
  default: '5.9.1'
# net_core_version - (Optional) Use to override the .NET Core version (defaults to 3.1.x)
- name: net_core_version 
  type: string 
  default: '3.1.x'

stages:
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.depends_on }} 
  condition: ${{ parameters.build_android_enabled }}
  variables: 
    - name: ANDROID_NDK_HOME
      value: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    - name: ANDROID_NDK_PATH
      value: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    - name: AndroidNdkDirectory
      value: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    - name: manifestPath
      value: ${{ parameters.android_manifest_filename }}
    - name: outputSearch
      value: ''

  pool:
    vmImage: 'windows-latest'

  jobs:
  - job: BuildAndroid
    steps:
    # Download the keystore from secure files with the name
    # specified in the parameter secure_file_keystore_filename
    - task: DownloadSecureFile@1
      displayName: 'Download secure file ${{ parameters.secure_file_keystore_filename }}'
      name: signing_keystore
      inputs:
        secureFile: '${{ parameters.secure_file_keystore_filename }}'

    # onStart steps - performed after any secure files are downloaded but before 
    # any other build steps are executed
    - ${{ parameters.onStart }}

    # This task looks at the application_package parameter and determines
    # whether the build output will be apk or aab
    - task: PowerShell@2
      displayName: 'Determine packaging format'
      inputs:
        targetType: 'inline'                                                                                                 
        script: |
          Write-Host "Determining what output format the build will generate"
          if( '${{ parameters.application_package }}'.contains(".aab") )
          { 
            $search = "**/*-Signed.aab"
            $format = "aab"
          }
          else {
            $search = "**/*-Signed.apk"
            $format = "apk"
          }
          Write-Host "Search for output using $search"
          Write-Host "##vso[task.setvariable variable=outputSearch]$search"
          Write-Host "Package format $format"
          Write-Host "##vso[task.setvariable variable=packageFormat]$format"

    # This task searches for the AndroidManifest.xml file so that the version information can be updated
    # The android_manifest_filename property can be used to set this location if the source code includes
    # multiple android projects
    - task: PowerShell@2
      displayName: 'Determine the location of the AndroidManifest.xml file'
      condition: and( succeeded(), eq( variables['manifestPath'], '') )
      inputs:
        targetType: 'inline'                                                                                                 
        script: |
          Write-Host "Finding Package Manifest (ie AndroidManifest.xml). Set android_manifest_filename parameter to override"
          $manifest = (Get-ChildItem -Filter "AndroidManifest.xml" -Path "$(System.DefaultWorkingDirectory)" -Recurse | Select-Object -First 1 ).FullName
          Write-Host "Found at $manifest"
          Write-Host "##vso[task.setvariable variable=manifestPath]$manifest"

    # Update the AndroidManifest.xml with the verion information
    - task: android-manifest-version@1
      displayName: 'Setting application version in $(manifestPath)'
      inputs:
        sourcePath: '$(manifestPath)'
        versionCodeOption: 'buildid'
        versionCode: '${{ parameters.build_number }}'
        versionName: '${{ parameters.full_version_number }}' 
        printFile: true

    # Check for solution filter - if filter, need to extract actual solution file
    - task: PowerShell@2
      displayName: 'Determine Solution File for ${{ parameters.solution_filename }}'
      inputs:
        targetType: 'inline'                                                                                                 
        script: |
          if( '${{ parameters.solution_filename }}'.contains(".slnf") ) {
              Write-Host "File specified is solution filter"
              $actualSolutionFile = (Get-Content -Path '${{ parameters.solution_filename }}' -RAW | ConvertFrom-Json).solution.path
              Write-Host "Solution relative path is $actualSolutionFile"
              $filterPath = (get-item '${{ parameters.solution_filename }}').directory.fullname 
              Write-Host "Filter path is $filterPath"
              $solutionFile = "$filterPath/$actualSolutionFile"
              Write-Host "Full path to solution file is $solutionFile"
              Write-Host "##vso[task.setvariable variable=solutionFilename]$solutionFile"
          }
          else{
              Write-Host "File specified is a solution file"
              $solutionFile = "${{ parameters.solution_filename }}"
              Write-Host "Full path to solution file is $solutionFile"
              Write-Host "##vso[task.setvariable variable=solutionFilename]$solutionFile"
          }


    # Install and Restore NuGet for the solution
    - template: ../steps/nuget-install-and-restore.yml
      parameters:
        nuget_version_to_install: '${{ parameters.android_nuget_version }}'
        solution_filename: '$(solutionFilename)' 

    # preBuild steps - performs steps prior to executing the solution build
    - ${{ parameters.preBuild }}

    # Build the solution
    - task: VSBuild@1
      displayName: 'Building solution ${{ parameters.solution_filename }}'
      inputs:
        solution: '${{ parameters.solution_filename }}'
        configuration: '${{ parameters.solution_build_configuration }}'
        msbuildArgs: '/p:platform="${{ parameters.solution_target_platform }}" 
        /p:AndroidBuildApplicationPackage="true" 
        /p:AndroidPackageFormat="$(packageFormat)"
        /p:AndroidKeyStore="True" 
        /p:AndroidSigningKeyStore="$(signing_keystore.secureFilePath)"
        /p:AndroidSigningKeyPass="${{ parameters.key_password }}" 
        /p:AndroidSigningKeyAlias="${{ parameters.key_alias }}" 
        /p:AndroidSigningStorePass="${{ parameters.keystore_password }}"' 

    # postBuild steps - performs steps immediately after executing the solution build
    - ${{ parameters.postBuild }}

    # Copy artifacts to the correct directory in the staging folder. It uses flattenFolders
    # so there is a risk that multiple artifacts could overwrite each other if they
    # have the same filename
    - task: CopyFiles@2
      displayName: 'Copying files to artifact folder ${{ parameters.artifact_folder }}'
      inputs:
        contents: '$(outputSearch)'
        targetFolder: '$(build.artifactStagingDirectory)/${{ parameters.artifact_folder }}'
        flattenFolders: true
        overWrite: true

    # Rename the application package to the name specified in the application_package parameter
    - task: PowerShell@2
      displayName: 'Rename application package'
      inputs:
        targetType: 'inline'                                                                                                 
        script: |
          if( '${{ parameters.application_package }}'.contains(".aab") ) {
            Get-ChildItem -Filter "*.aab" -Path "$(build.artifactStagingDirectory)/${{ parameters.artifact_folder }}"  -Recurse | Select-Object -First 1 | Rename-Item -NewName "${{ parameters.application_package }}" | Write-Host
          }
          else{
            Get-ChildItem -Filter "*.apk" -Path "$(build.artifactStagingDirectory)/${{ parameters.artifact_folder }}"  -Recurse | Select-Object -First 1 | Rename-Item -NewName "${{ parameters.application_package }}" | Write-Host
          }

    # prePublish steps - performs steps prior to publishing all artifacts from the staging directory
    - ${{ parameters.prePublish }}

    # Publish artifacts from this stage
    - task: PublishBuildArtifacts@1
      displayName: 'Publishing artifacts to ${{ parameters.artifact_name }}'
      inputs:
        pathtoPublish: '$(build.artifactStagingDirectory)' 
        artifactName: '${{ parameters.artifact_name }}' 
        publishLocation: Container

    # onEnd steps - performs steps after publishing artifacts, at the end of the build stage
    - ${{ parameters.onEnd }}
