parameters:
# stage_name - (Optional) The name of the stage, so that it can be referenced elsewhere (eg for dependsOn property). 
# Defaults to 'Build_Solution'
- name: stage_name
  type: string
  default: 'Build_Solution'
# depends_on - (Optional) The array of stages that this stage depends on. Default is that this stage does not depend on 
# any other stage
- name: depends_on
  type: string
  default: ''
# vm_image - (Optional) The name of the vm image to use for execution. Defaults to windows-2022
- name: vm_image
  type: string
  default: 'windows-2022'
# build_enabled - (Optional) Whether this stages should be executed. Note that setting this to false won't completely
# cancel the stage, it will merely skip most of the stages. The stage will appear to complete successfully, so
# any stages that depend on this stage will attempt to execute
- name: build_enabled
  type: boolean
  default: true

# solution_filename - (Required) The relative path to the solution file that should be built
- name: solution_filename
  type: string
# solution_build_configuration - (Optional) The build configuration within the solution that should be invoked. 
# Default is Release but can be overwritten if you want to do say a Debug build
- name: solution_build_configuration
  type: string
  default: Debug
# solution_target_platform - (Optional) The target platform that the solution build will use. 
# Defaults to 'x86'
- name: solution_target_platform
  type: string
  default: 'x86'

# artifact_name - (Optional) The name of the artifact to copy application to
- name: artifact_name
  type: string
  default: 'drop'
# artifact_folder - (Optional) The name of the folder to copy application to in the artifact
- name: artifact_folder
  type: string
  default: 'Solution'

# onStart - (Optional) Steps to be executed before stage starts
- name: onStart
  type: stepList
  default: []
# preBuild - (Optional) Steps to be executed before the build starts
- name: preBuild
  type: stepList
  default: []
# postBuild - (Optional) Steps to be executed after the build has been invoked
- name: postBuild
  type: stepList
  default: []
# prePublish - (Optional) Steps to be executed before application package is published to artifact
- name: prePublish
  type: stepList
  default: []
# onEnd - (Optional) Steps to be executed at the end of the stage
- name: onEnd
  type: stepList
  default: []

# windows_nuget_version - (Optional) Use to override the NuGet version (defaults to 6.0.0)
- name: windows_nuget_version
  type: string
  default: '6.0.0'
# net_core_version - (Optional) Use to override the .NET Core version (defaults to 6.0.x)
- name: net_core_version 
  type: string 
  default: '6.0.x'
# windows_sdk_version - (Optional) The version of the windows sdk to install (default '' for no installation)
- name: windows_sdk_version 
  type: string 
  default: ''

stages:
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.depends_on }} 
  condition: ${{ parameters.build_enabled }}


  pool:
    vmImage: '${{ parameters.vm_image }}'

  jobs:
  - job: BuildSolution

    steps:

    # onStart steps - performed after any secure files are downloaded but before 
    # any other build steps are executed
    - ${{ parameters.onStart }}

    ${{ if ne( parameters.windows_sdk_version , '') }}:
      - template: ../steps/windows/windows-sdk-install.yml
        parameters:
          name: DownloadInstallWindowsSdk
          windows_sdk_version: '${{ parameters.windows_sdk_version }}'

    # Check for solution filter - if filter, need to extract actual solution file
    - task: PowerShell@2
      displayName: 'Determine Solution File for ${{ parameters.solution_filename }}'
      inputs:
        targetType: 'inline'                                                                                                 
        script: |
          if( '${{ parameters.solution_filename }}'.contains(".slnf") ) {
              Write-Host "File specified is solution filter"
              $actualSolutionFile = (Get-Content -Path '${{ parameters.solution_filename }}' -RAW | ConvertFrom-Json).solution.path
              Write-Host "Solution relative path is $actualSolutionFile"
              $filterPath = (get-item '${{ parameters.solution_filename }}').directory.fullname 
              Write-Host "Filter path is $filterPath"
              $solutionFile = "$filterPath/$actualSolutionFile"
              Write-Host "Full path to solution file is $solutionFile"
              Write-Host "##vso[task.setvariable variable=solutionFilename]$solutionFile"

              Write-Host "Checking projects for wapproj for Windows fix"
              $buildproject = '${{ parameters.solution_filename }}'
              $projects = (Get-Content -Path '${{ parameters.solution_filename }}' -RAW | ConvertFrom-Json).solution.projects
              for($i=0;$i -lt $projects.length;$i++)
              {
                  $proj = $projects[$i]
                  Write-Host "Project - $proj" 
                  if($proj.contains('wapproj'))
                  {
                      $buildproject = $proj
                      $buildproject = "$filterPath/$buildproject"
                      Write-Host "Wapproj found - building $buildproject instead of solution"
                  }
              }
              Write-Host "##vso[task.setvariable variable=buildProjectOrSolution]$buildproject"
          }
          else{
              Write-Host "File specified is a solution file"
              $solutionFile = "${{ parameters.solution_filename }}"
              Write-Host "Full path to solution file is $solutionFile"
              Write-Host "##vso[task.setvariable variable=solutionFilename]$solutionFile"
              Write-Host "##vso[task.setvariable variable=buildProjectOrSolution]$solutionFile"
          }

    # Select the .Net Core version based on the net_core_version parameter          
    - task: UseDotNet@2
      displayName: 'Use .Net Core sdk ${{ parameters.net_core_version }}'
      inputs:
        version: '${{ parameters.net_core_version }}'

    # Install and Restore NuGet for the solution
    - template: ../steps/nuget-install-and-restore.yml
      parameters:
        nuget_version_to_install: '${{ parameters.windows_nuget_version }}'
        solution_filename: '$(solutionFilename)'

    # preBuild steps - performs steps prior to executing the solution build
    - ${{ parameters.preBuild }}

    # Build the solution
    - task: VSBuild@1
      displayName: 'Building solution ${{ parameters.solution_filename }}'
      inputs:
        solution: '$(buildProjectOrSolution)'
        msbuildArgs: '/p:platform="${{ parameters.solution_target_platform }}"' 
        configuration: '${{ parameters.solution_build_configuration }}'

    # postBuild steps - performs steps immediately after executing the solution build
    - ${{ parameters.postBuild }}

    # prePublish steps - performs steps prior to publishing all artifacts from the staging directory
    - ${{ parameters.prePublish }}
 
    # Publish artifacts from this stage
    - task: PublishBuildArtifacts@1
      displayName: 'Publishing artifacts to ${{ parameters.artifact_name }}'
      inputs:
        pathtoPublish: '$(build.artifactStagingDirectory)' 
        artifactName: '${{ parameters.artifact_name }}' 
        publishLocation: Container

    # onEnd steps - performs steps after publishing artifacts, at the end of the build stage
    - ${{ parameters.onEnd }}


