parameters:
# name - (Optional) The name prefix of all stages 
# Defaults to ''
- name: name
  type: string
  default: ''
# # depends_on - (Optional) The array of stages that this stage depends on. Default is that this stage does not depend on 
# # any other stage
# - name: depends_on
#   type: string
#   default: ''
# # vm_image - (Optional) The name of the vm image to use for execution. Defaults to windows-2022
# - name: vm_image
#   type: string
#   default: 'windows-2022'
# # build_enabled - (Optional) Whether this stages should be executed. Note that setting this to false won't completely
# # cancel the stage, it will merely skip most of the stages. The stage will appear to complete successfully, so
# # any stages that depend on this stage will attempt to execute
# - name: build_enabled
#   type: boolean
#   default: true

# solution_filename - (Required) The relative path to the solution file that should be built
- name: solution_filename
  type: string



- name: wasm_project_file
  type: string
  default: ''


# # solution_build_configuration - (Optional) The build configuration within the solution that should be invoked. 
# # Default is Release but can be overwritten if you want to do say a Debug build
# - name: solution_build_configuration
#   type: string
#   default: Debug
# # solution_target_platform - (Optional) The target platform that the solution build will use. 
# # Defaults to 'x86'
# - name: solution_target_platform
#   type: string
#   default: 'x86'

- name: solution_build_enabled
  type: boolean
  default: true

- name: ios_enabled
  type: boolean
  default: true
- name: uwp_enabled
  type: boolean
  default: true
- name: android_enabled
  type: boolean
  default: true
- name: wasm_enabled
  type: boolean
  default: true

- name: deploy_enabled
  type: boolean
  default: true

- name: full_version_number
  type: string
  default: '1.0.$(Build.BuildId)' 


- name: appsettings_securefile
  type: string
  default: ''

- name: appsettings_filename
  type: string
  default: 'appsettings.json'

- name: banner_enabled
  type: boolean
  default: false

- name: banner_image_expression
  type: string
  default: '**/*.png'

- name: banner_version_name_position
  type: string
  default: 'bottomRight'
  values:
  - none
  - bottomRight
  - bottomLeft
  - topLeft
  - topRight

- name: banner_version_name_text
  type: string
  default: ''

- name: banner_version_name_color
  type: string
  default: '#C5000D'

- name: banner_version_name_text_color
  type: string
  default: '#FFFFFF'

- name: banner_version_number_position
  type: string
  default: 'none'
  values:
  - none
  - top
  - bottom
  - center

- name: banner_version_number_text
  type: string
  default: ''

- name: banner_version_number_color
  type: string
  default: '#34424F'

- name: banner_version_number_text_color
  type: string
  default: '#FFFFFF'

# # artifact_name - (Optional) The name of the artifact to copy application to
# - name: artifact_name
#   type: string
#   default: 'drop'
# # artifact_folder - (Optional) The name of the folder to copy application to in the artifact
# - name: artifact_folder
#   type: string
#   default: 'Solution'

# # onStart - (Optional) Steps to be executed before stage starts
# - name: onStart
#   type: stepList
#   default: []
# # preBuild - (Optional) Steps to be executed before the build starts
# - name: preBuild
#   type: stepList
#   default: []
# # postBuild - (Optional) Steps to be executed after the build has been invoked
# - name: postBuild
#   type: stepList
#   default: []
# # prePublish - (Optional) Steps to be executed before application package is published to artifact
# - name: prePublish
#   type: stepList
#   default: []
# # onEnd - (Optional) Steps to be executed at the end of the stage
# - name: onEnd
#   type: stepList
#   default: []

# # windows_nuget_version - (Optional) Use to override the NuGet version (defaults to 6.0.0)
# - name: windows_nuget_version
#   type: string
#   default: '6.0.0'
# # net_core_version - (Optional) Use to override the .NET Core version (defaults to 6.0.x)
# - name: net_core_version 
#   type: string 
#   default: '6.0.x'
# # windows_sdk_version - (Optional) The version of the windows sdk to install (default '' for no installation)
# - name: windows_sdk_version 
#   type: string 
#   default: ''

stages:
- stage: '${{ parameters.name }}Print_Parameters'

  jobs:
  - job: PrintParameters

    steps:
    - task: Bash@3
      displayName: 'Parameters'
      condition: and( succeeded(), eq(variables['agent.diagnostic'], 'true') )
      inputs:
        targetType: inline
        script: |
          echo -------------------------------------------------------------
          echo -------------------------------------------------------------
          echo Name: "${{ parameters.name }}"
          echo Solution filename: "${{ parameters.solution_filename }}"
          echo Wasm project file: "${{ parameters.wasm_project_file }}"
          echo iOS enabled: "${{ parameters.ios_enabled }}"
          echo Uwp enabled: "${{ parameters.uwp_enabled }}"
          echo Android enabled: "${{ parameters.android_enabled }}"
          echo Wasm enabled: "${{ parameters.wasm_enabled }}"
          echo Deploy enabled: "${{ parameters.deploy_enabled }}"
          echo Full version number: "${{ parameters.full_version_number }}"
          echo Appsettings secure file: "${{ parameters.appsettings_securefile }}"
          echo Appsettings filename: "${{ parameters.appsettings_filename }}"
          echo Banner enabled: "${{ parameters.banner_enabled }}"
          echo Banner image expression: "${{ parameters.banner_image_expression }}"
          echo Banner version name position: "${{ parameters.banner_version_name_position }}"
          echo Banner version name text: "${{ parameters.banner_version_name_text }}"
          echo Banner version name color: "${{ parameters.banner_version_name_color }}"
          echo Banner version name text color: "${{ parameters.banner_version_name_text_color }}"
          echo Banner version number position: "${{ parameters.banner_version_number_position }}"
          echo Banner version number text: "${{ parameters.banner_version_number_text }}"
          echo Banner version number color: "${{ parameters.banner_version_number_color }}"
          echo Banner version number text color: "${{ parameters.banner_version_number_text_color }}"
          echo -------------------------------------------------------------
          echo -------------------------------------------------------------

- ${{ if parameters.solution_build_enabled }}:
  - template:  build-solution.yml
    parameters:
      # Stage name and whether it's enabled
      stage_name: '${{ parameters.name }}Build_Solution'
      depends_on: '${{ parameters.name }}Print_Parameters'
      # Solution to build
      solution_filename: ${{ parameters.solution_filename }}

- ${{ if eq( parameters.wasm_enabled, true ) }}:
  - template:  build-wasm.yml
    parameters:
      # Stage name and whether it's enabled
      stage_name: '${{ parameters.name }}Build_Wasm'
      ${{ if parameters.solution_build_enabled }}:
        depends_on: '${{ parameters.name }}Build_Solution'
      ${{ else }}:
        depends_on: '${{ parameters.name }}Print_Parameters'
      build_wasm_enabled: ${{ parameters.wasm_enabled }}
      # Version information
      full_version_number: ${{ parameters.full_version_number }}
      # Solution to build
      project_filename: ${{ parameters.wasm_project_file }}
      # Output information
      artifact_folder: 'Wasm'
      ${{ if or( ne( parameters.appsettings_securefile, '' ), eq( parameters.banner_enabled, true ) ) }}:
        preBuild:
          - template: ../steps/app-prebuild.yml
            parameters:
              appsettings_filename: ${{ parameters.appsettings_filename }}
              appsettings_securefile: ${{ parameters.appsettings_securefile }}
              solution_filename: ${{ parameters.solution_filename }}
              banner_enabled: ${{ parameters.banner_enabled }}
              banner_image_expression: '**/*SplaschScreen*.png'
              banner_version_name_position: '${{ parameters.banner_version_name_position }}'
              banner_version_name_text: '${{ parameters.banner_version_name_text }}'
              banner_version_name_color: '${{ parameters.banner_version_name_color }}'
              banner_version_name_text_color: '${{ parameters.banner_version_name_text_color }}'
              banner_version_number_position: '${{ parameters.banner_version_number_position }}'
              ${{ if ne( parameters.banner_version_number_text, '' ) }}:
                banner_version_number_text: '${{ parameters.banner_version_number_text }}'
              ${{ else }}:
                banner_version_number_text: '${{ parameters.full_version_number }}'
              banner_version_number_color: '${{ parameters.banner_version_number_color }}'
              banner_version_number_text_color: '${{ parameters.banner_version_number_text_color }}' 
