parameters:
# stage_name - (Optional) The name of the stage, so that it can be referenced elsewhere (eg for dependsOn property). 
# Defaults to 'Deploy_App_Center'
- name: stage_name
  type: string
  default: 'Deploy_App_Center'
# depends_on - (Optional) The array of stages that this stage depends on. Default is that this stage does not depend on 
# any other stage. However, since this is a deployment stage, you'll probably want to specify a build stage that
# this stage depends on.
- name: depends_on
  type: string
  default: ''
# vm_image - (Optional) The name of the vm image to use for execution. Defaults to windows-2022
- name: vm_image
  type: string
  default: 'windows-2022'
# deploy_appcenter_enabled - (Optional) Whether this stages should be executed. Note that setting this to false won't completely
# cancel the stage, it will merely skip most of the stages. The stage will appear to complete successfully, so
# any stages that depend on this stage will attempt to execute
- name: deploy_appcenter_enabled
  type: boolean
  default: true
# environment_name - (Optional) The environment to deploy to. Can be used to introduce a manual gate for approval for stage to proceed
- name: environment_name
  type: string
  default: 'Default Environment'

# artifact_name - (Optional) The name of the artifact to copy application from
- name: artifact_name
  type: string
  default: 'drop'
# artifact_folder - (Required) The name of the folder to copy application from in the artifact
- name: artifact_folder
  type: string
# application_package - (Required) The name of the application package to deploy
- name: application_package
  type: string

# appcenter_service_connection - (Required) The name of the service connection that connects Azure DevOps
# to App Center. Go to Service Connections in Azure DevOps to setup the connection and assign permissions
# for pipelines to access it
- name: appcenter_service_connection
  type: string
# appcenter_organisation - (Required) The organisation (or individual) in App Center that the application 
# is associated with. In AppCenter navigate to the application and extract organisation from URL
# eg https://appcenter.ms/users/[organisation]/apps/[applicationid]
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_organisation
  type: string
# appcenter_applicationid - (Required) The application id in App Center that identifies 
# the application. In AppCenter navigate to the application and extract application id from URL
# eg https://appcenter.ms/users/[organisation]/apps/[applicationid]
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_applicationid
  type: string
# appcenter_release_notes_option - (Optional) Whether release notes for App Center should be inputted via the appcenter_release_notes parameter
# or if it should come from a file (appcenter_release_notes_file parameter). 
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_release_notes_option
  type: string
  default: 'input'
  values: 
  - input
  - file
# appcenter_release_notes_source - (Optional) Whether release notes for App Center should be inputted from the source code 
# or from the artifact. Only if appcenter_release_notes_option is file.
- name: appcenter_release_notes_source
  type: string
  default: 'artifact'
  values: 
  - artifact
  - source_control
# appcenter_release_notes - (Optional) The release notes to be set in App Center for the release. 
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_release_notes
  type: string
  default: 'Default release notes'
# appcenter_release_notes_file - (Optional) The file to read the release notes from to be set in App Center for the release. 
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_release_notes_file
  type: string
  default: ''
# appcenter_is_mandatory_update - (Optional) Whether the App Center release should be marked as a mandatory update
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_is_mandatory_update
  type: boolean
  default: false
# appcenter_destination_type - (Optional) Whether the release is pushed out to a distribution group or a store
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_destination_type
  type: string
  default: 'groups'
  values: 
  - groups
  - store
# appcenter_distribution_group_ids - (Optional) The id(s) (comma separated list of guids) of the distribution groups to distribute the release to
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_distribution_group_ids
  type: string
  default: ''
# appcenter_destination_store_id - (Optional) The id of the destination store
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_destination_store_id
  type: string
  default: ''
# appcenter_dont_notify_testers - (Optional) Whether testers are notified about an App Center release
# More information at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops
- name: appcenter_dont_notify_testers
  type: boolean
  default: false

# secure_file_keystore_filename - (Optiona) IMPORTANT: This is required if application package is an AAB. 
# The keystore file used to sign the APK when extracte from an AAB. This is the name of the keystore in Secure Files. 
- name: secure_file_keystore_filename
  type: string
  default: ''
# keystore_alias - (Optional) IMPORTANT: This is required if application package is an AAB. The alias of the keystore. 
- name: keystore_alias
  type: string
  default: ''
# keystore_password - (Optional) IMPORTANT: This is required if application package is an AAB. The password to access the keystore
- name: keystore_password
  type: string
  default: ''

# onStart - (Optional) Steps to be executed before stage starts
- name: onStart
  type: stepList
  default: []
# postArtifactDownload - (Optional) Steps to be executed after artifacts from previous stages have been downloaded
- name: postArtifactDownload
  type: stepList
  default: []
# preAppCenterPublish - (Optional) Steps to be executed before application package is published to App Center
- name: preAppCenterPublish
  type: stepList
  default: []
# onEnd - (Optional) Steps to be executed at the end of the stage
- name: onEnd
  type: stepList
  default: []


stages:
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.depends_on }}
  condition: ${{ parameters.deploy_appcenter_enabled }} 

  jobs:
  - template: ../jobs/deploy/appcenter.yml
    parameters:
      environment_name: ${{ parameters.environment_name }}
      vm_image: '${{ parameters.vm_image }}'
      artifact_name: ${{ parameters.artifact_name }}
      artifact_folder: ${{ parameters.artifact_folder }}
      application_package: ${{ parameters.application_package }}
      appcenter_service_connection: ${{ parameters.appcenter_service_connection }}
      appcenter_organisation: ${{ parameters.appcenter_organisation }}
      appcenter_applicationid: ${{ parameters.appcenter_applicationid }}
      appcenter_release_notes_option: ${{ parameters.appcenter_release_notes_option }}
      appcenter_release_notes_source: ${{ parameters.appcenter_release_notes_source }}
      appcenter_release_notes: ${{ parameters.appcenter_release_notes }}
      appcenter_release_notes_file: ${{ parameters.appcenter_release_notes_file }}
      appcenter_is_mandatory_update: ${{ parameters.appcenter_is_mandatory_update }}
      appcenter_destination_type: ${{ parameters.appcenter_destination_typea }}
      appcenter_distribution_group_ids: ${{ parameters.appcenter_distribution_group_ids }}
      appcenter_destination_store_id: ${{ parameters.appcenter_destination_store_id }}
      appcenter_dont_notify_testers: ${{ parameters.appcenter_dont_notify_testers }}
      secure_file_keystore_filename: ${{ parameters.secure_file_keystore_filename }}
      keystore_alias: ${{ parameters.keystore_alias }}
      keystore_password: ${{ parameters.keystore_password }}
      onStart: ${{ parameters.onStart }}
      postArtifactDownload: ${{ parameters.postArtifactDownload }}
      prePublish: ${{ parameters.prePublish }}
      onEnd: ${{ parameters.onEnd }}

