parameters:
# stage_name - (Optional) The name of the stage, so that it can be referenced elsewhere (eg for dependsOn property). 
# Defaults to 'Deploy_Static_Web_App'
- name: stage_name
  type: string
  default: 'Deploy_Static_Web_App'
# depends_on - (Optional) The array of stages that this stage depends on. Default is that this stage does not depend on 
# any other stage. However, since this is a deployment stage, you'll probably want to specify a build stage that
# this stage depends on.
- name: depends_on
  type: string
  default: ''
# vm_image - (Optional) The name of the vm image to use for execution. Defaults to ubuntu-latest
- name: vm_image
  type: string
  default: 'ubuntu-latest'
# deploy_staticwebapp_enabled - (Optional) Whether this stages should be executed. Note that setting this to false won't completely
# cancel the stage, it will merely skip most of the stages. The stage will appear to complete successfully, so
# any stages that depend on this stage will attempt to execute
- name: deploy_staticwebapp_enabled
  type: boolean
  default: true
# environment_name - (Optional) The environment to deploy to. Can be used to introduce a manual gate for approval for stage to proceed
- name: environment_name
  type: string
  default: 'Default Environment'

# artifact_name - (Optional) The name of the artifact to copy application from
- name: artifact_name
  type: string
  default: 'drop'
# artifact_folder - (Required) The name of the folder to copy application from in the artifact
- name: artifact_folder
  type: string

# staticwebapp_token - (Required) The token for deployting a static web app
- name: staticwebapp_token
  type: string

# onStart - (Optional) Steps to be executed before stage starts
- name: onStart
  type: stepList
  default: []
# postArtifactDownload - (Optional) Steps to be executed after artifacts from previous stages have been downloaded
- name: postArtifactDownload
  type: stepList
  default: []
# preAppCenterPublish - (Optional) Steps to be executed before application package is published to App Center
- name: preAppCenterPublish
  type: stepList
  default: []
# onEnd - (Optional) Steps to be executed at the end of the stage
- name: onEnd
  type: stepList
  default: []


stages:
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.depends_on }}
  condition: ${{ parameters.deploy_staticwebapp_enabled }} 

  pool:
    vmImage: '${{ parameters.vm_image }}'

  jobs:
  - deployment: Deploy
    displayName: Deploy app to Static Web App
    environment: ${{ parameters.environment_name }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../steps/deploy/static-web-app.yml
            inputs:
              artifact_name: ${{ parameters.artifact_name }}
              artifact_folder: ${{ parameters.artifact_folder }}
              staticwebapp_token: ${{ parameters.staticwebapp_token }}
              onStart: ${{ parameters.onStart }}
              postArtifactDownload: ${{ parameters.postArtifactDownload }}
              prePublish: ${{ parameters.prePublish }}
              onEnd: ${{ parameters.onEnd }}

